/**
 * Code Generator Service - v10
 * 代码生成服务：支持 JavaScript 和 Python 代码生成
 */
class CodeGenerator {

  /**
   * 生成 JavaScript 代码
   * @param {Object} workflow - 工作流对象
   * @returns {string} JavaScript 代码
   */
  generateJavaScript(workflow) {
    const name = this.sanitizeName(workflow.name || 'Workflow');
    const functionName = this.toCamelCase(name);
    
    let code = `// AI Creator Workflow - ${workflow.name || '未命名工作流'}
// Generated by AI Creator H5 v10
// Date: ${new Date().toISOString()}

`;

    // 生成辅助函数
    code += this.generateHelperFunctions('js');
    
    // 生成工作流执行函数
    code += `async function ${functionName}(inputs = {}) {
  const results = {};
  const context = { inputs, results, timestamp: Date.now() };
  
  console.log('[${name}] 开始执行工作流');
`;

    // 生成节点执行代码
    const sortedNodes = this.topologicalSort(workflow);
    sortedNodes.forEach(node => {
      code += this.nodeToJSFunction(node, workflow);
    });

    code += `
  console.log('[${name}] 工作流执行完成');
  return results;
}
`;

    // 添加调用示例
    code += this.generateUsageExample(functionName, 'js');
    
    return code;
  }

  /**
   * 生成 Python 代码
   * @param {Object} workflow - 工作流对象
   * @returns {string} Python 代码
   */
  generatePython(workflow) {
    const name = this.sanitizeName(workflow.name || 'Workflow');
    const functionName = this.toSnakeCase(name);
    
    let code = `# AI Creator Workflow - ${workflow.name || '未命名工作流'}
# Generated by AI Creator H5 v10
# Date: ${new Date().toISOString()}

import asyncio
import json
from typing import Dict, Any, Optional
from datetime import datetime

`;

    // 生成辅助函数
    code += this.generateHelperFunctions('python');
    
    // 生成工作流执行函数
    code += `async def ${functionName}(inputs: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    ${workflow.description || workflow.name || '工作流'} 执行函数
    
    Args:
        inputs: 输入参数字典
        
    Returns:
        执行结果字典
    """
    if inputs is None:
        inputs = {}
    
    results = {}
    context = {
        "inputs": inputs,
        "results": results,
        "timestamp": datetime.now().isoformat()
    }
    
    print(f'[${name}] 开始执行工作流')
`;

    // 生成节点执行代码
    const sortedNodes = this.topologicalSort(workflow);
    sortedNodes.forEach(node => {
      code += this.nodeToPythonFunction(node, workflow);
    });

    code += `
    print(f'[${name}] 工作流执行完成')
    return results
`;

    // 添加调用示例
    code += this.generateUsageExample(functionName, 'python');
    
    return code;
  }

  /**
   * 单个节点转为 JS 函数
   */
  nodeToJSFunction(node, workflow) {
    const nodeName = this.getNodeName(node);
    const indent = '  ';
    
    // 获取输入连接
    const inputs = workflow.connections
      .filter(c => c.to === node.id && c.toPort === 'in')
      .map(c => {
        const fromNode = workflow.nodes.find(n => n.id === c.from);
        return fromNode ? `results['${c.from}']?.output` : null;
      })
      .filter(Boolean);
    
    const config = this.formatConfig(node.config);
    
    return `
  // 节点: ${nodeName}
  console.log('[${nodeName}] 执行中...');
  results['${node.id}'] = await executeNode('${node.subtype}', {
    ${inputs.length > 0 ? `inputs: ${inputs[0]},` : ''}
    ${config}
  });
`;
  }

  /**
   * 单个节点转为 Python 函数
   */
  nodeToPythonFunction(node, workflow) {
    const nodeName = this.getNodeName(node);
    
    // 获取输入连接
    const inputs = workflow.connections
      .filter(c => c.to === node.id && c.toPort === 'in')
      .map(c => {
        const fromNode = workflow.nodes.find(n => n.id === c.from);
        return fromNode ? "results['" + c.from + "']['output']" : null;
      })
      .filter(Boolean);
    
    const config = this.formatConfigPython(node.config);
    
    let configStr = '';
    if (inputs.length > 0 || config) {
      configStr = "    params = {\n";
      if (inputs.length > 0) {
        configStr += "      'inputs': " + inputs[0] + ",\n";
      }
      if (config) {
        configStr += "      " + config + "\n";
      }
      configStr += "    }\n";
    }
    
    return `
  # 节点: ${nodeName}
  print(f'[{nodeName}] 执行中...')
  ` + (configStr ? "params = " + configStr.replace('    params = ', '') : '') + `
  results['${node.id}'] = await execute_node('${node.subtype}', ` + (configStr ? 'params' : '{}') + `)
`;
  }

  /**
   * 生成工作流执行器代码
   */
  generateWorkflowRunner(language = 'js') {
    if (language === 'python') {
      return `

# ============ 工作流执行器 ============

async def execute_node(node_type: str, params: Dict[str, Any]) -> Dict[str, Any]:
    """
    执行单个节点
    
    Args:
        node_type: 节点类型
        params: 执行参数
        
    Returns:
        执行结果
    """
    node_handlers = {
        'manual': lambda p: {'success': True, 'output': {'message': '手动触发'}},
        'character': lambda p: {'success': True, 'output': {'characterId': f'char-{int(time.time())}'}},
        'music': lambda p: {'success': True, 'output': {'musicId': f'music-{int(time.time())}'}},
        'tts': lambda p: {'success': True, 'output': {'ttsId': f'tts-{int(time.time())}'}},
        'poster': lambda p: {'success': True, 'output': {'posterId': f'poster-{int(time.time())}'}},
        'forLoop': lambda p: {'success': True, 'output': {'iterations': p.get('count', 3)}},
        'whileLoop': lambda p: {'success': True, 'output': {'iterations': 3}},
        'condition': lambda p: {'success': True, 'output': {'branch': 'true'}},
        'subflowCall': lambda p: {'success': True, 'output': {'subflowId': p.get('workflowId')}},
    }
    
    handler = node_handlers.get(node_type)
    if handler:
        return await handler(params)
    else:
        return {'success': False, 'error': f'Unknown node type: {node_type}'}
`;
    }
    
    return `
// ============ 工作流执行器 ============

async function executeNode(nodeType, params) {
  const nodeHandlers = {
    'manual': (p) => ({ success: true, output: { message: '手动触发' } }),
    'character': (p) => ({ success: true, output: { characterId: 'char-' + Date.now() } }),
    'music': (p) => ({ success: true, output: { musicId: 'music-' + Date.now() } }),
    'tts': (p) => ({ success: true, output: { ttsId: 'tts-' + Date.now() } }),
    'poster': (p) => ({ success: true, output: { posterId: 'poster-' + Date.now() } }),
    'forLoop': (p) => ({ success: true, output: { iterations: p.count || 3 } }),
    'whileLoop': (p) => ({ success: true, output: { iterations: 3 } }),
    'condition': (p) => ({ success: true, output: { branch: 'true' } }),
    'subflowCall': (p) => ({ success: true, output: { subflowId: p.workflowId } }),
  };

  // 模拟异步执行
  await new Promise(resolve => setTimeout(resolve, 100));
  
  const handler = nodeHandlers[nodeType];
  if (handler) {
    return handler(params);
  } else {
    return { success: false, error: 'Unknown node type: ' + nodeType };
  }
}
`;
  }

  /**
   * 生成辅助函数
   */
  generateHelperFunctions(language) {
    if (language === 'python') {
      return `import time

def log_message(message, level="info"):
    """日志记录"""
    timestamp = datetime.now().strftime("%H:%M:%S")
    print(f"[{timestamp}] [{level.upper()}] {message}")

def format_output(data):
    """格式化输出"""
    return json.dumps(data, ensure_ascii=False, indent=2)
`;
    }
    
    return `
// 日志记录
function logMessage(message, level = 'info') {
  const timestamp = new Date().toLocaleTimeString('zh-CN');
  console.log(\`[\${timestamp}] [\${level.toUpperCase()}] \${message}\`);
}

// 格式化输出
function formatOutput(data) {
  return JSON.stringify(data, null, 2);
}
`;
  }

  /**
   * 生成使用示例
   */
  generateUsageExample(functionName, language) {
    if (language === 'python') {
      return `

# ============ 使用示例 ============

if __name__ == '__main__':
    async def main():
        # 定义输入
        test_inputs = {
            'topic': '测试主题',
            'style': '古风'
        }
        
        # 执行工作流
        result = await ${functionName}(test_inputs)
        
        # 输出结果
        print('\\n执行结果:')
        print(format_output(result))
    
    # 运行
    asyncio.run(main())
`;
    }
    
    return `
// ============ 使用示例 ============

// 执行工作流
${functionName}({
  topic: '测试主题',
  style: '古风'
}).then(result => {
  console.log('执行结果:', formatOutput(result));
}).catch(error => {
  console.error('执行失败:', error);
});
`;
  }

  /**
   * 拓扑排序节点
   */
  topologicalSort(workflow) {
    const nodes = [...workflow.nodes];
    const connections = workflow.connections || [];
    
    // 计算入度
    const inDegree = {};
    nodes.forEach(n => inDegree[n.id] = 0);
    connections.forEach(c => {
      if (inDegree[c.to] !== undefined) {
        inDegree[c.to]++;
      }
    });
    
    // 找到入度为0的节点
    const queue = nodes.filter(n => inDegree[n.id] === 0);
    const sorted = [];
    
    while (queue.length > 0) {
      const node = queue.shift();
      sorted.push(node);
      
      // 移除该节点的出边
      connections.forEach(c => {
        if (c.from === node.id) {
          inDegree[c.to]--;
          if (inDegree[c.to] === 0) {
            queue.push(nodes.find(n => n.id === c.to));
          }
        }
      });
    }
    
    // 如果有循环依赖，追加剩余节点
    const remaining = nodes.filter(n => !sorted.includes(n));
    return [...sorted, ...remaining];
  }

  /**
   * 获取节点名称
   */
  getNodeName(node) {
    const names = {
      manual: '手动触发',
      character: '角色生成',
      music: '配乐生成',
      tts: '配音生成',
      poster: '海报生成',
      loop: '循环',
      condition: '条件判断',
      forLoop: 'For循环',
      whileLoop: 'While循环',
      doWhileLoop: 'Do-While循环',
      subflowCall: '子流程调用'
    };
    return node.name || names[node.subtype] || node.subtype;
  }

  /**
   * 格式化配置对象
   */
  formatConfig(config) {
    if (!config || Object.keys(config).length === 0) {
      return '';
    }
    
    return Object.entries(config)
      .map(([key, value]) => {
        const formattedValue = typeof value === 'string' ? `'${value}'` : value;
        return `${key}: ${formattedValue}`;
      })
      .join(',\n    ');
  }

  /**
   * 格式化配置对象 (Python)
   */
  formatConfigPython(config) {
    if (!config || Object.keys(config).length === 0) {
      return '';
    }
    
    return Object.entries(config)
      .map(([key, value]) => {
        const formattedValue = typeof value === 'string' ? `'${value}'` : value;
        return `'${key}': ${formattedValue}`;
      })
      .join(',\n      ');
  }

  /**
   * 清理名称（移除特殊字符）
   */
  sanitizeName(name) {
    return name.replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, '').trim();
  }

  /**
   * 转为驼峰命名
   */
  toCamelCase(str) {
    const cleaned = this.sanitizeName(str);
    return cleaned.charAt(0).toLowerCase() + cleaned.slice(1);
  }

  /**
   * 转为蛇形命名
   */
  toSnakeCase(str) {
    const cleaned = this.sanitizeName(str);
    return cleaned.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
  }
}

// 导出单例
const codeGenerator = new CodeGenerator();
